export { default as home } from './home.png'
export { default as game } from './game.png'
export { default as sports } from './sports.png'
export { default as tech } from './tech.png'
export { default as music } from './music.png'
export { default as blog } from './blog.png'
export { default as news } from './news.png'
export { default as person } from './person.png'
export { default as automobile} from './automobile.png'
export { default as mrbeast } from './mrbeast.png'
export { default as pew } from './pew.png'
export { default as pari } from './parithabam.png'
export { default as thumbnail1} from './thumbnail1.png'
export { default as thumbnail2} from './thumbnail2.png'
export { default as thumbnail3} from './thumbnail3.png'
export { default as thumbnail4} from './thumbnail4.png'
export { default as thumbnail5} from './thumbnail5.png'
export { default as thumbnail6} from './thumbnail6.png'
export { default as thumbnail7} from './thumbnail7.png'